name: weather_application
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  geolocator:
  http:
  flutter_spinkit:
  anim_search_bar:
  weather_icons:
  flutter_weather_bg_null_safety:
  permission_handler:
  lottie:
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - animations/cloud.json
    - animations/rain.json
    - animations/sunny.json
    - animations/fog.json
    - animations/thinder.json
    - animations/snow.json

  fonts:
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Regular.ttf
